version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - misspell
    - nilerr
    - noctx
    - rowserrcheck
    - unconvert
    - usestdlibvars
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.DB).Close

formatters:
  enable:
    - gofmt
    - goimports
