// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: exercises.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createExercise = `-- name: CreateExercise :one
insert into swol.exercises (user_id, name)
values ($1, $2)
returning id, user_id, name, created_at
`

type CreateExerciseParams struct {
	UserID *uuid.UUID `json:"userId"`
	Name   string     `json:"name"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise, arg.UserID, arg.Name)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
select id, user_id, name, created_at from swol.exercises
where user_id is null or user_id = $1
order by lower(name)
`

func (q *Queries) ListExercises(ctx context.Context, userID *uuid.UUID) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
