// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type SessionStatus string

const (
	SessionStatusActive    SessionStatus = "active"
	SessionStatusPaused    SessionStatus = "paused"
	SessionStatusCompleted SessionStatus = "completed"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"swolSessionStatus"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type WeightUnit string

const (
	WeightUnitLb WeightUnit = "lb"
	WeightUnitKg WeightUnit = "kg"
)

func (e *WeightUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WeightUnit(s)
	case string:
		*e = WeightUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for WeightUnit: %T", src)
	}
	return nil
}

type NullWeightUnit struct {
	WeightUnit WeightUnit `json:"swolWeightUnit"`
	Valid      bool       `json:"valid"` // Valid is true if WeightUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWeightUnit) Scan(value interface{}) error {
	if value == nil {
		ns.WeightUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WeightUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWeightUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WeightUnit), nil
}

type Exercise struct {
	ID        uuid.UUID  `json:"id"`
	UserID    *uuid.UUID `json:"userId"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"createdAt"`
}

type Goal struct {
	ID                   uuid.UUID  `json:"id"`
	UserID               uuid.UUID  `json:"userId"`
	ExerciseID           uuid.UUID  `json:"exerciseId"`
	TargetWeight         float64    `json:"targetWeight"`
	Unit                 WeightUnit `json:"unit"`
	TargetWeightKg       *float64   `json:"targetWeightKg"`
	TargetReps           int32      `json:"targetReps"`
	CompletedAt          *time.Time `json:"completedAt"`
	CompletedMilestoneID *uuid.UUID `json:"completedMilestoneId"`
	CreatedAt            time.Time  `json:"createdAt"`
	UpdatedAt            time.Time  `json:"updatedAt"`
}

type Milestone struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"userId"`
	ExerciseID uuid.UUID  `json:"exerciseId"`
	SessionID  *uuid.UUID `json:"sessionId"`
	Weight     float64    `json:"weight"`
	Unit       WeightUnit `json:"unit"`
	WeightKg   *float64   `json:"weightKg"`
	Reps       int32      `json:"reps"`
	AchievedAt time.Time  `json:"achievedAt"`
	Note       *string    `json:"note"`
	CreatedAt  time.Time  `json:"createdAt"`
}

type SessionNote struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"sessionId"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
}

type UserAchievement struct {
	UserID          uuid.UUID `json:"userId"`
	AchievementCode string    `json:"achievementCode"`
	UnlockedAt      time.Time `json:"unlockedAt"`
}

type UserSettings struct {
	UserID     uuid.UUID  `json:"userId"`
	WeightUnit WeightUnit `json:"weightUnit"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
}

type WorkoutSession struct {
	ID              uuid.UUID     `json:"id"`
	UserID          uuid.UUID     `json:"userId"`
	Status          SessionStatus `json:"status"`
	StartedAt       time.Time     `json:"startedAt"`
	PausedAt        *time.Time    `json:"pausedAt"`
	PausedSeconds   int64         `json:"pausedSeconds"`
	EndedAt         *time.Time    `json:"endedAt"`
	LegacyCheckinID *int64        `json:"legacyCheckinId"`
	CreatedAt       time.Time     `json:"createdAt"`
	UpdatedAt       time.Time     `json:"updatedAt"`
}
