// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	GetOrCreateUserSettings(ctx context.Context, userID uuid.UUID) (UserSettings, error)
	ListExercises(ctx context.Context, userID *uuid.UUID) ([]Exercise, error)
	UpdateWeightUnit(ctx context.Context, arg UpdateWeightUnitParams) (UserSettings, error)
}

var _ Querier = (*Queries)(nil)
