// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getOrCreateUserSettings = `-- name: GetOrCreateUserSettings :one
insert into swol.user_settings (user_id)
values ($1)
on conflict (user_id) do update set user_id = excluded.user_id
returning user_id, weight_unit, created_at, updated_at
`

func (q *Queries) GetOrCreateUserSettings(ctx context.Context, userID uuid.UUID) (UserSettings, error) {
	row := q.db.QueryRow(ctx, getOrCreateUserSettings, userID)
	var i UserSettings
	err := row.Scan(
		&i.UserID,
		&i.WeightUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWeightUnit = `-- name: UpdateWeightUnit :one
insert into swol.user_settings (user_id, weight_unit)
values ($1, $2)
on conflict (user_id) do update set weight_unit = excluded.weight_unit, updated_at = now()
returning user_id, weight_unit, created_at, updated_at
`

type UpdateWeightUnitParams struct {
	UserID     uuid.UUID  `json:"userId"`
	WeightUnit WeightUnit `json:"weightUnit"`
}

func (q *Queries) UpdateWeightUnit(ctx context.Context, arg UpdateWeightUnitParams) (UserSettings, error) {
	row := q.db.QueryRow(ctx, updateWeightUnit, arg.UserID, arg.WeightUnit)
	var i UserSettings
	err := row.Scan(
		&i.UserID,
		&i.WeightUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
